language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

jdk:
  - oraclejdk8
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ant ; fi

before_script:
 - git clone https://github.com/jshobe-inetsoft/java-cef.git src
 - cd src && mkdir jcef_build && cd jcef_build

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -G "Xcode" -DPROJECT_ARCH="x86_64" .. ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j4 ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project jcef.xcodeproj -configuration Release -target ALL_BUILD ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../tools && ./compile.sh linux64 ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./make_distrib.sh linux64 || true ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../tools && ./make_distrib.sh macosx64 || true ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../binary_distrib && zip -r java-cef-linux64.zip linux64 ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../binary_distrib && zip -r java-cef-macosx64.zip macosx64 ; fi
